function [trainedClassifiers, modelList, validationAccuracies] = trainClassifier2(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: a matrix with the same number of columns and data type
%       as imported into the app.
%
%  Output:
%      trainedClassifier: a struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: a function to make predictions on new
%       data.
%
%      validationAccuracy: a double containing the accuracy in percent. In
%       the app, the History list displays this overall accuracy score for
%       each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a matrix containing only the predictor columns used for
% training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 13-Jul-2020 13:15:56

modelList=cell(1,1);
ctr =1;
% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
% Convert input to table
%inputTable = array2table(trainingData, 'VariableNames', {'column_1', 'column_2', 'column_3'});
inputTable = trainingData;
% predictorNames = {'column_1', 'column_2'};
% predictors = inputTable(:, predictorNames);
% response = inputTable.column_3;
% isCategoricalPredictor = [false, false];
predictorNames = inputTable.Properties.VariableNames(1:end-1);
predictors = inputTable(:, predictorNames);
response = inputTable.predictor;
% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationDiscriminant = fitcdiscr(...
    predictors, ...
    response, ...
    'DiscrimType', 'linear', ...
    'Gamma', 0, ...
    'FillCoeffs', 'off', ...
    'ClassNames', [1; 2; 3; 4]); %make this more general, maybe input range

% Create the result struct with predict function
%predictorExtractionFcn = @(x) array2table(x, 'VariableNames', predictorNames);
predictorExtractionFcn = @(t) t(:, predictorNames);
discriminantPredictFcn = @(x) predict(classificationDiscriminant, x);
trainedClassifiers{ctr}.predictFcn = @(x) discriminantPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifiers{ctr}.ClassificationDiscriminant = classificationDiscriminant;
trainedClassifiers{ctr}.About = 'This struct is a trained model exported from Classification Learner R2019a.';
trainedClassifiers{ctr}.HowToPredict = sprintf('To make predictions on a new predictor column matrix, X, use: \n  yfit = c.predictFcn(X) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nX must contain exactly 2 columns because this model was trained using 2 predictors. \nX must contain only predictor columns in exactly the same order and format as your training \ndata. Do not include the response column or any columns you did not import into the app. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');
trainedClassifiers{ctr}.model_name = 'linear discriminant';
modelList{ctr}=trainedClassifiers{ctr}.model_name;
% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
% Convert input to table
%inputTable = array2table(trainingData, 'VariableNames', {'column_1', 'column_2', 'column_3'});

% predictorNames = {'column_1', 'column_2'};
% predictors = inputTable(:, predictorNames);
% response = inputTable.column_3;
% isCategoricalPredictor = [false, false];

% Perform cross-validation
partitionedModel = crossval(trainedClassifiers{ctr}.ClassificationDiscriminant, 'KFold', 5);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracies(ctr) = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
